### ISSUE TITLE
8. Setup base project

### ISSUE THREAD

**Issue by ILLUSIONack** [buzzzlightyear/special-park#28]
**User story**
As a `Developer` I want to be able to `have a base project ` so that ` everything is al setup and ready to go`.

**Tasks**
- [x] Create a GIT repository and add all
members as collaborators
- [x] Setup framework for REST API
- [x] Setup framework for front-end website
- [x] Setup framework for back-end website
- [x] Setup database

**Acceptance criteria**
- An GitHub repository with correct 
folders, inside each folder the designated
project files.
