### ISSUE TITLE
9. Make proof of concept

### ISSUE THREAD

**Issue by ILLUSIONack** [buzzzlightyear/special-park#29]
**User story**
As a `Product Owner` I want to be able to `have a detailed version of the Proof of Concept ` so that ` know the ins and out of the product and see if its worth investing in`.

**Tasks**
- [x] Document the problem statement and elaborate
about the market opportunities
- [x] Mention stakeholders
- [x] Context of the problem
- [x] Describe the proof of concept solution
- [x] Planning and development process
- [x] functional requirements
- [x] non functional requirements

**Acceptance criteria**
- A well documented PoC
