### ISSUE TITLE
10. Design client website

### ISSUE THREAD

**Issue by ahmadkurdo** [buzzzlightyear/special-park#30]
**User story**
As a `Developer` I want to be able to `have a design for the client website` so that `I know how the pages should look like`. 

**Tasks**
- [x] Design landing page
- [x] Design authentication page
- [x] Design register page
- [x] Design customer panel

**Acceptance criteria**
- A .xd file with all the different designs
from all the different pages
