### ISSUE TITLE
Configure Raspberry Pi 4

### ISSUE THREAD

**Issue by buzzzlightyear** [buzzzlightyear/special-park#34]
**User story**
As a `developer` I want to be able to `configure the Raspberry Pi and attach sensors to it` so that `have a working Raspberry Pi (technical component)`.

**Tasks**
- [x] Install Raspbian
- [x] Connect PIR sensor
- [x] Connect LED lights
- [x] Connect Camera
- [x] Test if every sensor work

**Acceptance criteria**
- Every sensor works
- The Raspberry Pi is ready
