### ISSUE TITLE
User authentication with REST API

### ISSUE THREAD

**Issue by ahmadkurdo** [buzzzlightyear/special-park#36]
**User story**
As a `Web developer` I want to be able to `register a users with the REST API` so that ` users can create accounts and login from the website with a API request`.

**Tasks**
- [x] Implement API sign up endpoint where users can register.
- [x] Implement API login endpoint where users can login.
- [x] Implement API login endpoint where users can login.
- [x] Implement token auhtorization and authentication.

**Acceptance criteria**
- Users can  register and login.
- Users get a API key after logging in.
