### ISSUE TITLE
Django Tests

### ISSUE THREAD

**Issue by buzzzlightyear** [buzzzlightyear/special-park#37]
**User story**
As a `developer` I want to be able to `have a good working software` so that `know nothing is broken and everything works`.

**Tasks**
- [x] Integrate Travis CI with this GitHub repository
- [x] Run test on every push in every branch
- [x] Make tests for Users (login, register)
- [x] Make tests for Parking Logic (entering, leaving, invalid requests)
- [x] Make tests for CRUD license plate (create, read, update, delete license plates)

**Acceptance criteria**
- Parts of the Users components get tested
- Parts of the Parking Logic components get tested
- Parts of the CRUD license plate components get tested
