### ISSUE TITLE
Make software for the Raspberry Pi 4

### ISSUE THREAD

**Issue by buzzzlightyear** [buzzzlightyear/special-park#38]
**User story**
As a `developer` I want to be able to `connect the Raspberry Pi to the REST API` so that `the Raspberry Pi can grant access to the parking garage`.

**Tasks**
- [ ] Extract license plates with the camera module attached to the Raspberry Pi
- [ ] Send requests including the extracted license plate
- [ ] Create LED messages with the LED lights (green for good, red for incorrect or no access, yellow for loading)
- [ ] Process the responses with the LED messages
- [ ] Detect motion and only then run the camera module

**Acceptance criteria**
- When motion gets detected a LED message is shown for loading, the camera function will be triggered and requests will be sent
- The response get handled with the correct LED message
