### ISSUE TITLE
User authentication with Express backend

### ISSUE THREAD

**Issue by ILLUSIONack** [buzzzlightyear/special-park#39]
**User story**
As a `Web developer` I want to be able to `send user authentication requests to the REST api` so that ` users can create accounts, login and navigate on the website`.

**Tasks**
- [x] Implement registratie API request
- [x] Implement login API request
- [x] Implement sign out on back-end through clearing cookies
- [x] Implement cookie saving on the client browser for future requests
- [x] Implement navigation for all web designed web pages

**Acceptance criteria**
- User must be able to register an account and login with same credentials
- A cookie must be saved on browser so a user remains loged in
- During sign out the user should be redirected to the landing page and the cookies should be deleted
- All the website pages must have navigation buttons to the other
