### ISSUE TITLE
CRUD operations for user cars with the REST API

### ISSUE THREAD

**Issue by ahmadkurdo** [buzzzlightyear/special-park#40]
**User story**
As a `Web developer` I want to be able to `create, read, delete and update users car's ` so that `I can implement CRUD functionalities in the website`.

**Tasks**
- [x] Implement endpoint for users cars.
- [x] Read all cars from the endpoint.
- [x] Add a car with the endpoint.
- [x] Delete a car with the endpoint.
- [x] Update a car with the endpoint.

**Acceptance criteria**
- CRUD operations can be done with the REST API to the cars which are owned by the user.
