### ISSUE TITLE
Implement the design for the client website in HTML

### ISSUE THREAD

**Issue by ILLUSIONack** [buzzzlightyear/special-park#42]
**User story**
As a `Developer ` I want to be able to `design the client website pages in HTML ` so that `these pages are visible and user friendly `.

**Tasks**
- [x] Design registration page
- [x] Design login page
- [x] Design forgot-password page
- [x] Design landing page
- [x] Design dashboard page

**Acceptance criteria**
- All the pages must be user friendly and simple
- Registration page must have email and password field
- The registration page must also have a button redirecting to the login page
- The login page must have name, email, password fields and a login button redirecting to the dashboard. It should also have a forgot password button which redirects to the forgot password page
- The landing page must have a button which navigates to user registration
