### ISSUE TITLE
Make a technical report

### ISSUE THREAD

**Issue by buzzzlightyear** [buzzzlightyear/special-park#43]
**User story**
As a `teacher` I want to be able to `read a technical report` so that `I can read the contents of the applications and grade the project`.

**Tasks**
- [x] the wishes of the PO / requirements
- [x] what you have made
- [x] which toolchain you have used
- [x] which parts (software / hardware) you have developed
- [x] how these components work together (diagram(s) with explanation)
- [x] the essential algorithms (how does the navigation / sound threshold determination / fall detection / ... work)
- [x] which improvement points came up during the testing of your PoC
- [x] which improvement points have you already addressed and which are still open
- [x] the special things that the follow-up team should pay attention to
- [x] briefly explain the folder structure of the code in an attachment (where is it located).

**Acceptance criteria**
- A well written Technical Report.
