### ISSUE TITLE
Implement login as admin

### ISSUE THREAD

**Issue by ILLUSIONack** [buzzzlightyear/special-park#47]
**User story**
As a `User` I want to be able to `login as admin` so that `I can delete or edit user accounts `.

**Tasks**
- [ ] Add Admin credentials into database
- [ ] Implement admin validation on every route and redirect relevant page
- [ ] Implement admin page with list of all users

**Acceptance criteria**
- On the admin should be able to navigate to user accounts page
