### ISSUE TITLE
Admin and garage owner creation by admin users

### ISSUE THREAD

**Issue by ahmadkurdo** [buzzzlightyear/special-park#56]
**User story**
As a `web developer` I want to be able to `create admins and garage owner` so that `their roles are separated from each other `.

**Tasks**
- [x] Create admin endpoint
- [x] Grant access to admin users only in the endpoint
- [x] Implement admin creation within the endpoint
- [x] Implement garage owner creation within the endpoint

**Acceptance criteria**
- A endpoint that is only accessible by admins in which new admins as wel as new garage owners can be created
