### ISSUE TITLE
User role seperation 

### ISSUE THREAD

**Issue by ahmadkurdo** [buzzzlightyear/special-park#66]
**User story**
As a ` Web developer` I want to be able to `know the role of each user ` so that `I can redirect them to their views`.

**Tasks**
- [x] Create admin role
- [x] Create garage owner role
- [x] Create user role

**Acceptance criteria**
- Al users have their own roles
